name: Builds Frontend
on:
  workflow_call:
    # Required inputs
    inputs:
      env:
        required: true
        type: string
  workflow_dispatch:
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        # Checkout code from repository
        uses: actions/checkout@v3

      - name: Cache node modules
        # Restores the build from cache to speed up build process
        uses: actions/cache@v3
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ github.sha }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn

      - name: Build application
        run: yarn build

      - name: Move files to build folder
        # Moved files are used in Docker build
        run: |
          if [ "${{ inputs.env }}" == "dev" ]; then
            mv apps/web/.env.development .env.production
          else
            mv apps/web/.env.production .env.production
          fi
          mkdir build
          mv apps/web/.next/standalone build/standalone
          mv apps/web/.next/static build/standalone/.next/static
          mv apps/web/public build/public
          mv node_modules build/node_modules
          mv .env.production build/.env.production

      - name: Cache build
        # Caches the built image for future builds
        uses: actions/cache@v3
        env:
          cache-name: cache-build-${{ github.run_id }}
        with:
          path: ./build
          key: build-${{ github.run_id }}
          restore-keys: build-${{ github.run_id }}

      - name: Create a upload-build
        # Creates a folder to upload to artifact
        shell: bash
        run: |
          cp -r build upload-build

      - name: Remove standalone from build
        # Removes files not needed for the assets.
        shell: bash
        run: |
          rm -rf upload-build/standalone
          rm -rf upload-build/node_modules

      #  Uploads the upload-build to artifact
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: upload-build
