name: Deploys to S3
on:
  workflow_call:
    inputs:
      env:
        required: false
        default: dev
        type: string
      type:
        required: false
        default: branch
        type: string
      build_number:
        required: false
        type: string
      aws_region:
        required: false
        type: string
        default: us-east-1
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      cloudfront_id:
        required: false
      asset_bucket:
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.4.0

      - name: Restore build from cache
        uses: actions/cache@v3
        env:
          cache-name: cache-build-${{ github.run_id }}
        with:
          path: ./build
          key: build-${{ github.run_id }}
          restore-keys: build-${{ github.run_id }}

      - name: Remove standalone from build
        shell: bash
        run: |
          rm -rf build/standalone
          rm -rf build/node_modules

      - name: Extract branch and commit
        shell: bash
        run: |
          export REF="${{ github.ref || 'refs/heads/main' }}"
          echo "##[set-output name=branch;]$(echo ${REF#refs/heads/} | rev | cut -d '/' -f '1' | rev | tr '[:upper:]' '[:lower:]')"
          echo "##[set-output name=commit;]$(git rev-parse --short "$GITHUB_SHA")"
        id: extract_branch

      - name: Get Calculated Vars
        shell: bash
        run: |
          if [[ "${{ inputs.type }}" == "build" ]]; then export DEST=builds/${GITHUB_RUN_ID}/portal; fi
          if [[ "${{ inputs.type }}" == "main" ]]; then export DEST=portal; fi
          echo "##[set-output name=dest;]$(echo "$DEST")"

          export S3_BUCKET="${{ inputs.asset_bucket }}"
          echo "##[set-output name=bucket;]$(echo "$S3_BUCKET")"

          echo "##[set-output name=cloudfront_id;]$(echo "${{ secrets.cloudfront_id }}")"
        id: vars

      - name: Deploy 🚀
        uses: prewk/s3-cp-action@v2
        with:
          aws_region: ${{ inputs.aws_region }}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          source: ./build
          dest: s3://verto-dev-assets/${{ github.ref_name }}
          flags: --recursive
