name: Builds Frontend
on:
  workflow_call:
    # Required inputs
    inputs:
      env:
        required: true
        type: string
      domain:
        required: true
        type: string
      assets_domain:
        required: true
        type: string
      is_protected:
        required: false
        type: boolean
        default: false
  workflow_dispatch:
jobs:
  build-frontend: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        # Checkout code from repository
        uses: actions/checkout@v3

      - name: Cache node modules
        # Restores the build from cache to speed up build process
        uses: actions/cache@v3
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ github.sha }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn

      - name: Build application
        run: APP_ENV=development yarn build