name: Builds and Prepares for Deployment
on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  repository_dispatch:
    types: [dev]
  # Trigger the workflow on workflow dispatch
  workflow_dispatch:
# Concurrency for the workflow
concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  # Job to install dependencies and run lint checks
  install-and-lint:
    uses: vertotrade/verto.ui/.github/workflows/action-install-lint.yml@main

  # Job to build the UI/Next.js
  build:
    uses: vertotrade/verto.ui/.github/workflows/action-build.yml@main
    needs: [install-and-lint]
    # Passes the environment variable "env" with value "dev" to the action
    with:
      env: dev

  # Job to build the backend/Docker
  be-build:
    uses: vertotrade/verto.ui/.github/workflows/action-build-backend.yml@main
    needs: [build]
    with:
      ecr_repo: verto-dev-ui-nginx
