name: Prepares deployment artifacts / Deploys to DEV.
on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  repository_dispatch:
    types: [dev]
  # Trigger the workflow on workflow dispatch
  workflow_dispatch:
# Concurrency for the workflow
concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  # Job to install dependencies and run lint checks
  install-and-lint:
    uses: vertotrade/verto.ui/.github/workflows/action-install-lint.yml@main

  # Job to build the UI/Next.js
  build:
    uses: vertotrade/verto.ui/.github/workflows/action-build.yml@main
    needs: [install-and-lint]
    # Passes the environment variable "env" with value "dev" to the action
    with:
      env: dev
      domain: dev.vertotrade.com
      assets_domain: assets.vertotrade.com
      is_protected: true

  # Job to build the backend/Docker
  be-build:
    uses: vertotrade/verto.ui/.github/workflows/action-build-backend.yml@main
    needs: [build]
    with:
      ecr_repo: verto-dev-ui-nginx


  # Job to dispatch dev deployment.
  dispatch-dev-deployment:
    runs-on: ubuntu-latest
    needs: [be-build]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.VERTO_APP_DEPLOY_PAT }}
          repository: vertotrade/verto.deploy
          event-type: deployDev
          client-payload: '{"build_number": "${{ github.run_number }}" }'