name: Deploys to Prod
on:
  workflow_dispatch:
concurrency:
  group: prod_environment
  cancel-in-progress: false

jobs:
  # Job to install dependencies and run lint checks
  install-lint:
    uses: vertotrade/verto.ui/.github/workflows/action-install-lint.yml@main

  # Job to build the UI/Next.js
  build:
    uses: vertotrade/verto.ui/.github/workflows/action-build.yml@main
    needs: [install-and-lint]
    # Passes the environment variable "env" with value "dev" to the action
    with:
      env: prod

  # Job to build the backend/Docker
  be-build:
    uses: vertotrade/verto.ui/.github/workflows/action-build-backend.yml@main
    needs: [build]
    with:
      ecr_repo: verto-prod-ui-nginx

  # Job to publish the built backend/Docker image to ECR
  be-publish-prod:
    uses: vertotrade/verto.ui/.github/workflows/action-push-ecr-image.yml@main
    needs: [be-build]
    with:
      aws_region: us-east-1
      build_number: ${{ github.run_id }}
      ecr_repo: verto-prod-ui-nginx
    secrets:
      aws_access_key_id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

  # This job deploys the backend using AWS ECS
  be-deploy-prod:
    uses: vertotrade/verto.ui/.github/workflows/action-deploy-ecs.yml@main
    needs: [be-publish-prod]
    # The following inputs are passed to the AWS ECS deployment action
    with:
      env: prod
      task_definition: ./apps/web/task-definition.json
      aws_region: us-east-1
      ecr_repo: verto-prod-ui-nginx
      service: verto-prod-ui-nginx
      cluster: verto-prod-ui-ecs-fargate
      aws_log_group: /verto/ecs/prod/ui-nginx
      task_role_arn: arn:aws:iam::517696922803:role/dropmint-prod-ecs-task-role
      task_execution_role_arn: arn:aws:iam::517696922803:role/dropmint-prod-ecs-task-execution-role
    secrets:
      aws_access_key_id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

  # This job deploys to teh assets bucket of the project
  fe-deploy-prod:
    uses:
      vertotrade/verto.ui/.github/workflows/action-deploy-s3.yml@main
      # This job needs the frontend environment to be built
      # Will run simunteniously with be-build
    needs: [build]
    with:
      env: prod
      type: main
      aws_region: us-east-1
    secrets:
      aws_access_key_id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      asset_bucket: verto-prod-assets
      cloudfront_id: ${{ secrets.PROD_CLOUDFRONT_ID }}
